extends: 
  - "@redhat-cloud-services/eslint-config-redhat-cloud-services"
  - 'plugin:cypress/recommended'
globals:
  insights: 'readonly'
  shallow: readonly
  render: 'readonly'
  mount: 'readonly'
rules:
  react/jsx-no-useless-fragment: error