const SET_GLOBAL_FILTER_TAGS = 'SET_GLOBAL_FILTER_TAGS';
const SET_GLOBAL_FILTER_WORKLOADS = 'SET_GLOBAL_FILTER_WORKLOADS';
const SET_GLOBAL_FILTER_SIDS = 'SET_GLOBAL_FILTER_SIDS';

export default {
  SET_GLOBAL_FILTER_TAGS,
  SET_GLOBAL_FILTER_WORKLOADS,
  SET_GLOBAL_FILTER_SIDS,
};
